### PR TITLE
Dynamic patches API

### PR DESCRIPTION
**Pull request by mersinvald**
This change allows clients to configure `evm` in runtime, getting us closer to the network-agnostic API.

Dynamic Patch API is a cornerstone for runtime configuration by the client code that uses `evm`, like `multi-geth` for instance.
This PR moves us away from fully-static configuration, and adds a DynamicPatch type that is runtime-configurable.

`DynamicPatch` still implements the `Patch` interface, just as well as the previous `static` patches in `network-*` crates. Static patches are left supported at this point too and there's no measurable performance drop for static patches (at least on my hardware).

### CODE REVIEW

**Comment by sorpaas** [comment]
I don't understand why you need `Clone` on patch. It should always be taken by reference?

**Comment by mersinvald** [comment]
@sorpaas tried to avoid Clone, but it's needed for ~VM::derive~ VM::with_previous, where the `Patch` object (and other parameters) get copied to the new VM. I also tried to use `Cow` and borrowing to achieve zero-copy patches, but that majorly limits API usage (I couldn't get `stateful` to compile, at all).

I could though make Patch require `Copy`, not `Clone`, but IMO that would limit our options in the future, and `DynamicPatch` is a rather big object to have it copied uncontrollably.

Maybe zero-copy `Patch` could be done

**Comment by sorpaas** [comment]
@mersinvald No. Just use reference everywhere. Make struct accept a lifetime modifier and use that for every patch.

**Comment by sorpaas** [comment]
> I could though make Patch require Copy

Technically the compiler can and will optimize move for Copy, and we should have implemented Copy when it is appropriate. But as you pointed out, I think using Copy here wouldn't be a good idea.

**Comment by mersinvald** [comment]
@sorpaas tried that with reference, the API is not usable if we have a lifetime there. It brings way more complexity then there's profit.

Though hang on, I just got an idea, there might be a way to get away with just borrows and moves without lifetimes in public interface and Copy/Clone.

**Comment by mersinvald** [comment]
@sorpaas no, the `with_previous` can be done without any copies, there's a redundant referencing (that was my idea here). 

But `Machine::derive` requires copying now.

If you think that it may be reasonably implemented with just references, I'll try again and will send you the code so we could discuss it hands on :))

Putting this PR on hold for now.

**Comment by mersinvald** [comment]
@sorpaas you were right, thanks for the catch. All inner crates compile and work well with borrowed patch.

I need to check how would the evm-ffi API feel about the references, then if everything adds up nicely, I'll move forward with this PR.

Thanks again, if you have any other comments -- it's highly appreciated.

**Comment by mersinvald** [comment]
Okay, since the issue with `Clone` have been sorted out, let's continue here.

@sorpaas @r8d8, rewiew?

**Comment by sorpaas** [comment]
LGTM.

**Review by r8d8 — APPROVED** [review]
LGTM

**Pull request merged**
